---
- name: get the status and verification code
  hosts: elkservers
  become: true

  tasks:
    - shell: "systemctl status kibana"
      register: shell_result

    - debug:
        var: shell_result.stdout_lines