---
- name: get the enrollment token
  hosts: elkservers
  become: true

  tasks:
    - shell: "/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana"
      register: shell_result

    - debug:
        var: shell_result.stdout_lines